config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  resources :members, only: [:show] do
    collection do
      get "edit_description", to: "members#edit_description", as: :edit_description
      patch "update_description", to: "members#update_description", as: :update_description
      get "edit_personal_details", to: "members#edit_personal_details", as: :edit_personal_details
      patch "update_personal_details", to: "members#update_personal_details", as: :update_personal_details
    end
  end

  resources :work_experiences
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :work_experiences, dependent: :destroy

  PROFILE_TITLE = [
    'Product Manager',
    'Senior Developer',
    'Mid-Level Developer',
    'Junior Developer'
  ].freeze

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def address
    "#{city} #{state} #{country}".strip
  end

  def self.ransackable_attributes(auth_object = nil)
    ["city", "country"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/work_experience.rb
class WorkExperience < ApplicationRecord
  belongs_to :user
  EMPLOYMENT_TYPE = ['Full-time', 'Part-time', 'Self-employed', 'Freelance', 'Trainee', 'Internship'].freeze
  LOCATION_TYPE = ['On-site', 'Hybrid', 'Remote'].freeze

  validates :company, :start_date, :job_title, :location, presence: true
  validates :employment_type, presence: true, inclusion: { in: EMPLOYMENT_TYPE, message: 'not a valid employment type'}
  validates :location_type, presence: true, inclusion: { in: LOCATION_TYPE, message: 'not a valid location type'}
  validate :work_experience_last_date
  validate :presence_of_end_date
  validate :end_date_greater_than_start_date, if: :currently_not_working_here?

  def work_experience_last_date
    if end_date.present? && currently_working_here
      errors.add(:end_date, 'must be blank if you are currently working in this company')
    end
  end

  def presence_of_end_date
    if end_date.nil? && !currently_working_here
      errors.add(:end_date, 'must be present if you are not currently working in this company')
    end
  end

  def currently_not_working_here?
    !currently_working_here
  end

  def end_date_greater_than_start_date
    return if end_date.nil?

    if end_date < start_date
      errors.add(:end_date, 'must be greater than start_date')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.limit(16).order(created_at: :desc)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!, only: %[:edit_description, :update_description, :edit_personal_details, :update_personal_details]

  def show
    @user = User.find(params[:id])
  end

  def edit_description
  end

  def update_description
    respond_to do |format|
      if current_user.update(about: params[:user][:about])
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace('member-description', partial: 'members/member_description', locals: { user: current_user  })
        }
      end
    end
  end

  def edit_personal_details
  end

  def update_personal_details
    respond_to do |format|
      if current_user.update(user_personal_details_params)
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace('member-personal-details', partial: 'members/member_personal_details', locals: { user: current_user  })
        }
      end
    end
  end

  private

  def user_personal_details_params
    params.require(:user).permit(:first_name, :last_name, :city, :state, :country, :zipcode, :profile_title)
  end
end

app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_work_experience, only: %i[edit update destroy]

  def new
    @work_experience = current_user.work_experiences.new
  end

  def edit
  end

  def create
    @work_experience = current_user.work_experiences.new(work_experience_params)
    respond_to do |format|
      if @work_experience.save
        format.turbo_stream { render turbo_stream: turbo_stream.append('work_experience_items',
          partial: 'work_experiences/work_experience', locals: { work_experience: @work_experience })}
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            'remote_modal',
            partial: 'shared/turbo_modal',
            locals: { form_partial: 'work_experiences/form',
            modal_title: 'Add new work experience' })
        }
      end
    end
  end

  def update
  end

  def destroy
  end

  private

  def set_work_experience
    @work_experience = current_user.work_experiences.find(params[:id])
  end

  def work_experience_params
    params.require(:work_experience).permit(:start_date, :end_date, :currently_working_here, :company, :employment_type,
      :location, :location_type, :description, :user_id, :job_title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container mx-auto mt-5">
    <div class="row">
        <div class="col-lg-12">
            <div class="card mt-4 mb-4">
                <div class="card-body">
                    <h3 class="text-center mb-3">Search professionals across the world!</h3>
                    <%= search_form_for @q, url: root_path do |form| %>
                        <div class="input-group mb-3">
                            <%= form.search_field :city_or_country_cont,
                                class: "form-control",
                                placeholder: "Search by country or city",
                                area: { label: "Search by country or city", describedby: "button-addon2" }
                            %>
                            <%= form.submit "Search", class: "btn btn-primary", id: "button-addon2"  %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4 mb-4">
        <% @users.each do |user| %>
            <div class="col-lg-3 mb-3 mt-3">
                <div class="card text-center shadow">
                    <div class="card-body">
                        <%= image_tag "user.png", style: "width: 150px; border-radius: 50%; border: 2px solid #0d6efd; cursor: pointer", class: 'mb-3' %>
                        <div class="user-info">
                            <h5 style="min-height: 50px" ><%= user.full_name %></h5>
                            <p class="lead" style="min-height: 60px" ><%= user.profile_title %></p>
                            <small class="text-primary"><%= user.country %></small><br />
                            <%= link_to "View Profile", member_path(user) , class: "btn btn-primary mt-3" %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevCommunity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="mx-auto">
      <%= render "shared/header" %>
    </div>

    <div class="mx-auto">
      <%= yield %>
      <%= turbo_frame_tag 'remote_modal' %>
    </div>

    <div class="mx-auto">
        <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/members/_description_modal.html.erb
<%= form_with model: current_user, url: update_description_members_path, method: :patch do |form| %>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="mb-3">Edit your description here. Try to keep it simple and to the point.</label>
                    <%= form.text_area :about, value: current_user.about, class: "form-control", rows: 15 %>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" data-action="click->bootstrap-modal#submitEnd">Close</button>
        <%= form.submit 'Save Changes', class: 'btn btn-primary', data: { action: 'click->bootstrap-modal#submitEnd'} %>
    </div>
<% end %>

app/views/members/_member_description.html.erb
<p class="lead" id="member-description"><%= user.about %> </p>

app/views/members/_member_personal_details.html.erb
<div class="card mb-5" id="member-personal-details">
    <div class="row">
        <div class="col-lg-4">
            <%= image_tag "user.png", class: "img-fluid" %>
        </div>
        <div class="col-lg-8">
            <div class="card-body">
                <% if user_signed_in? && user == current_user %>
                    <div class="col-lg-6">
                        <div class="d-flex justify-content-end">
                            <%= link_to edit_personal_details_members_path,
                                data: { controller: "bootstrap-modal-form" } do %>
                                <i class="bi bi-pencil-fill"></i>
                            <% end %>
                        </div>
                    </div>
                <% end %>
                <h3 class="fw-bold"><%= user.full_name %> </h3>
                <p class="lead"><%= user.profile_title  %> </p>
                <p class="lead text-primary"><%= user.address  %> </p>
            </div>
        </div>
    </div>
</div>

app/views/members/_personal_info_modal.html.erb
<%= form_with model: current_user, url: update_personal_details_members_path, method: :patch do |form| %>
    <div class="modal-body">

        <div class="form-group mb-3">
            <label class="form-label">First name</label>
            <%= form.text_field :first_name, value: current_user.first_name, class: "form-control" %>
        </div>

        <div class="form-group  mb-3">
            <label class="form-label">Last name</label>
            <%= form.text_field :last_name, value: current_user.last_name, class: "form-control" %>
        </div>

        <div class="form-group  mb-3">
            <label class="form-label">Profile title</label>
            <%= form.text_field :profile_title, value: current_user.profile_title, class: "form-control" %>
        </div>

        <div class="form-group  mb-3">
            <label class="form-label">City</label>
            <%= form.text_field :city, value: current_user.city, class: "form-control" %>
        </div>

        <div class="form-group  mb-3">
            <label class="form-label">State</label>
            <%= form.text_field :state, value: current_user.state, class: "form-control" %>
        </div>

        <div class="form-group  mb-3">
            <label class="form-label">Country</label>
            <%= form.text_field :country, value: current_user.country, class: "form-control" %>
        </div>

        <div class="form-group  mb-3">
            <label class="form-label">Zipcode</label>
            <%= form.text_field :zipcode, value: current_user.zipcode, class: "form-control" %>
        </div>

    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" data-action="click->bootstrap-modal#submitEnd">Close</button>
        <%= form.submit 'Save Changes', class: 'btn btn-primary', data: { action: 'click->bootstrap-modal#submitEnd'} %>
    </div>
<% end %>

app/views/members/edit_description.turbo_stream.erb
<%= turbo_stream.replace 'remote_modal' do %>
    <%= render 'shared/turbo_modal', modal_title: 'Edit your description', form_partial: 'members/description_modal' %>
<% end %>

app/views/members/edit_personal_details.turbo_stream.erb
<%= turbo_stream.replace 'remote_modal' do %>
    <%= render 'shared/turbo_modal', modal_title: 'Edit your personal info', form_partial: 'members/personal_info_modal' %>
<% end %>

app/views/members/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12 mx-auto mt-5">
            <%= render 'member_personal_details', user: @user %>

            <div class="card mb-5">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="d-flex justify-content-start">
                                <h3>About</h3>
                            </div>
                        </div>
                        <% if user_signed_in? && @user == current_user %>
                            <div class="col-lg-6">
                                <div class="d-flex justify-content-end">
                                    <%= link_to edit_description_members_path, data: { controller: "bootstrap-modal-form" } do %>
                                        <i class="bi bi-pencil-fill"></i>
                                    <% end %>
                                </div>
                            </div>
                        <% end %>
                    </div>

                    <%= render 'member_description', user: @user %>
                </div>
            </div>

            <div class="card mb-5">
                <div class="card-body">
                    <% if user_signed_in? && @user == current_user %>
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="d-flex justify-content-start">
                                    <h3>Work Experiences</h3>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="d-flex justify-content-end">
                                    <%= link_to new_work_experience_path, data: { controller: "bootstrap-modal-form" } do %>
                                        <i class="bi bi-plus"></i> Add Experience
                                    <% end %>
                                </div>
                            </div>

                            <% if @user.work_experiences.present? %>
                                <div class="col-lg-4">
                                    <div class="d-flex justify-content-end">
                                        <%= link_to "javascript:void(0)" do %>
                                            <i class="bi bi-pencil-fill"></i> Edit Experiences
                                        <% end %>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    <% end %>

                    <% if @user.work_experiences.present? %>
                        <ul class="list-group" id="work_experience_items">
                            <% @user.work_experiences.each do |work_experience| %>
                                <%= render 'work_experiences/work_experience', work_experience: work_experience %>
                            <% end %>
                        </ul>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="container py-5">
    <div class="row">
      <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
      </div>

      <div class="col-md-5 offset-md-1 mb-3">
        <form>
          <h5>Subscribe to our newsletter</h5>
          <p>Monthly digest of what's new and exciting from us.</p>
          <div class="d-flex flex-column flex-sm-row w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Email address</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
            <button class="btn btn-primary" type="button">Subscribe</button>
          <div data-lastpass-icon-root="true" style="position: relative !important; height: 0px !important; width: 0px !important; float: left !important;"></div></div>
        </form>
      </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p>© 2023 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
      </ul>
    </div>
  </footer>

app/views/shared/_header.html.erb
<div class="container">
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Dev Community", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Profile", member_path(current_user), class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out",
              destroy_user_session_path,
              data: { turbo_method: :delete, turbo_confirm: 'Are you sure want to sign out?' },
              class: "nav-link active" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</div>

app/views/shared/_turbo_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
    <!-- Modal -->
    <div class="modal fade" id="bootstrapTurboModalCenter" tabindex="-1"
        role="dialog" aria-labelledby="bootstrapTurboModalCenterTitle" aria-hidden="true" data-controller="bootstrap-modal">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="bootstrapTurboModalLongTitle"><%= modal_title %></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" data-action="click->bootstrap-modal#submitEnd">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <%= render form_partial %>
            </div>
        </div>
    </div>
<% end %>

app/views/work_experiences/_form.html.erb
<%= form_with model: @work_experience, method: :post do |form| %>
    <div class="modal-body">
        <div class="row">
            <% if @work_experience.errors.any? %>
                <div class="error-area" style="color:red;">
                    <h3><% pluralize(@work_experience.errors.count, 'error') %> prohibited your work experience from being
                    saved.</h3>
                    <ul>
                        <% @work_experience.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="col-lg-12">
                <div class="form-group">
                    <label class="form-label mb-2 mt-3">
                        Job title
                        <span class="text-danger">*</span>
                    </label>
                    <%= form.text_field :job_title, class: "form-control" %>
                </div>

                <div class="form-group">
                    <label class="form-label mb-2 mt-3">
                        Company
                        <span class="text-danger">*</span>
                    </label>
                    <%= form.text_field :company, class: "form-control" %>
                </div>

                <div class="form-group">
                    <label class="form-label mb-2 mt-3">
                        Employment Type
                        <span class="text-danger">*</span>
                    </label>
                    <%= form.select :employment_type,
                        options_for_select(WorkExperience::EMPLOYMENT_TYPE),
                        { prompt: 'Select employment type' },
                        { class: "form-select" }
                    %>
                </div>

                <div class="form-group">
                    <label class="form-label mb-2 mt-3">
                        Location
                        <span class="text-danger">*</span>
                    </label>
                    <%= form.text_field :location, class: "form-control" %>
                </div>

                <div class="form-group">
                    <label class="form-label mb-2 mt-3">
                        Location Type
                        <span class="text-danger">*</span>
                    </label>
                    <%= form.select :location_type,
                        options_for_select(WorkExperience::LOCATION_TYPE),
                        { prompt: 'Select location type' },
                        { class: "form-select" }
                    %>
                </div>

                <div class="form-group row">
                    <div class="col-lg-6">
                        <label class="form-label mb-2 mt-3">
                            Start Date
                            <span class="text-danger">*</span>
                        </label>
                        <%= form.date_field :start_date, class: "form-control" %>
                    </div>
                    <div class="col-lg-6">
                        <label class="form-label mb-2 mt-3">
                            End Date
                            <span class="text-danger">*</span>
                        </label>
                        <%= form.date_field :end_date, class: "form-control" %>
                    </div>

                    <div class="col-lg-6">
                        <div class="form-check form-switch mb-2 mt-3">
                            <%= form.check_box :currently_working_here, class: "form-check-input", role: "switch" %>
                            <label class="form-check-label">I am currently working here</label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-label mb-2 mt-3">Description</label>
                    <%= form.text_area :description, class: "form-control", rows: 5 %>
                </div>

            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" data-action="click->bootstrap-modal#submitEnd">Close</button>
        <%= form.submit 'Save Changes', class: 'btn btn-primary', data: { action: 'click->bootstrap-modal#submitEnd'} %>
    </div>
<% end %>

app/views/work_experiences/_work_experience.html.erb
<li class="list-group-item" id="work_experience_item_<%= work_experience.id %>">
    <div class="row">
        <div class="col-lg-9">
            <div class="d-flex justify-content-start">
                <p class="fw-bold">
                    <%= work_experience.job_title %>
                </p>
            </div>
        </div>
        <div class="col-lg-3">

        </div>
    </div>
    <small><%= work_experience.company %></small><br />
    <small><%= work_experience.employment_type %></small><br />
    <small><%= work_experience.location %></small><br />
</li>

app/views/work_experiences/new.turbo_stream.erb
<%= turbo_stream.replace 'remote_modal' do %>
    <%= render 'shared/turbo_modal', modal_title: 'Add new work experience', form_partial: 'work_experiences/form' %>
<% end %>